version: "3"
services:
    redis:
        container_name: redis
        image: redis
        restart: always
        ports:
            - "${REDIS_PORT}:6379"
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        command: redis-server --requirepass $REDIS_PASSWORD
    redis-commander:
        container_name: redis-commander
        image: rediscommander/redis-commander
        restart: always
        ports:
            - "${REDIS_COMMANDER_PORT}:8081"
        depends_on:
            - redis
        environment:
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - REDIS_PORT=${REDIS_PORT}
        - HTTP_USER=${REDIS_COMMANDER_USER}
        - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD}
    # nest:
    #     container_name: nest
    #     restart: always
    #     build:
    #         dockerfile: Dockerfile
    #         context: ./
    #     env_file: 
    #         - .env
    #     ports:
    #         - ${PORT}:8000
